#!name=qq音乐去广告 @zqzess
#!desc=屏蔽qq音乐开屏广告

[Rule]
DOMAIN,adstats.tencentmusic.com,REJECT
DOMAIN,ad.tencentmusic.com,REJECT
DOMAIN,adcdn.tencentmusic.com,REJECT
DOMAIN,adexpo.tencentmusic.com,REJECT
DOMAIN,adclick.tencentmusic.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,monitor.music.qq.com,REJECT
DOMAIN,stat.y.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,oth.str.mdt.qq.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN-SUFFIX,imtmp.net,REJECT
DOMAIN,sdk.e.qq.com,REJECT
DOMAIN,p.l.qq.com,REJECT
DOMAIN,us.l.qq.com,REJECT
DOMAIN,tangram.e.qq.com,REJECT